#!/bin/bash
####################################################################
### FUNCTIONS
####################################################################
function build_tools()
{
sed -e "s:^F77*=\"gfortran\":F77=\"$1\":"  \
    -e "s:^CC*=\"gcc\":CC=\"$2\":" \
    -e "s:BIGMEM=\"true\":BIGMEM=\"false\":"  maketools > maketools.buildbot

chmod +x maketools.buildbot

./maketools.buildbot clean            $HERE_T

cd prenek
sed -e 's:\([0-9]\) \([0-9]\):\1\2:g'\
    -e '4s:[0-9][0-9]*:10 000:'         basics.inc > t.t
mv basics.inc basics.inc_old
mv t.t basics.inc

cd ../
./maketools.buildbot all     $HERE_T  | tee $3

#put all back
cd prenek
mv basics.inc_old basics.inc
cd ../
rm maketools.buildbot
}
####################################################################
function moveLog()
{
#Find all log files and error files and put into directory
mv ../../examples/*/*log.*     $1
mv ../../examples/*/*.err*     $1
}
####################################################################
function submake()
{
sed -e "s:^F77*=\"mpif77\":F77=\"$1\":"  \
    -e "s:^CC*=\"mpicc\":CC=\"$2\":"  \
    -e "s:\#IFMPI*=:IFMPI=:"  makenek > makenek.bb
chmod +x makenek.bb
}
####################################################################
### PARAMETERS
####################################################################
echo "####################################################################"
echo "### INPUT PARAMETERS"
echo "####################################################################"
# take input parameters
#args=("$@")
#argsnr=$#

echo "### SERIAL COMPILER"
echo ${F77_SRL}
echo ${CC_SRL}

echo "### PARALLEL COMPILER"
echo ${F77_MPI}
echo ${CC_MPI}

echo "### MATLAB PATH"
echo ${MATLAB}

echo "### MOAB LIBRARIES AND PATH"
echo ${MOAB_LIB}
echo ${MOAB_DIR_SRL}
echo ${MOAB_DIR_PAR}


# Local directory
HERE=`pwd`
echo "Local dir " $HERE
echo ""

# Check list of parameters
if [ "${F77_SRL}" == "" -o "${F77_SRL}" = "" ]
then
    echo "ERROR: No serial compiler; requred to compile tools"
    exit 1
fi

IF_MPI="on"
if [ "${F77_MPI}" == "" -o "${F77_MPI}" = "" ]
then
    echo "WARNING: No parallel compiler; parallel tests turned off"
    IF_MPI="off"
fi
IF_MOAB="on"
if [ "${MOAB_LIB}" == "" -o "${MOAB_DIR_SRL}" = "" ]
then
    echo "WARNING: Some MOAB data missing; MOAB tests turned off"
    echo "WARNING: Check MOAB C compiler flags and MOAB directory in makenek"
    IF_MOAB="off"
fi

if [ "${IF_MPI}" == "on" -a "${MOAB_DIR_PAR}" = "" ]
then
    echo "WARNING: Parallel MOAB data missing; MOAB tests turned off"
    IF_MOAB="off"
fi

IF_MATLAB="on"
if [ "${MATLAB}" == "" ]
then
    echo "WARNING: Matlab executable missing; AMG tests turned off"
    IF_MATLAB="off"
fi

if [ "${IF_MOAB}" == "on" ]
then
# change MOAB paths to use it in sed
    MOAB_LIB_S=$(echo $MOAB_LIB | sed -e "s:\/:\\\/:g" -e "s:\.:\\\.:g")
    MOAB_DIR_SRL_S=$(echo $MOAB_DIR_SRL | sed -e "s:\/:\\\/:g" -e "s:\.:\\\.:g")
    if [ "${IF_MPI}" == "on" ]
    then
       MOAB_DIR_PAR_S=$(echo $MOAB_DIR_PAR | sed -e "s:\/:\\\/:g" -e "s:\.:\\\.:g")
    fi
fi

####################################################################
### Create Directories
####################################################################
echo "####################################################################"
echo "### CREATE DIRECTORIES"
echo "####################################################################"

# tools
mkdir -v tools

# serial logs
mkdir -v srlLog
mkdir -v srl2Log

if [ "${IF_MPI}" == "on" ]
then
# parallel logs
    mkdir -v mpiLog
    mkdir -v mpi2Log
fi

# Path for tools directory
cd tools
HERE_T=`pwd`
cd ../../

####################################################################
### File tweaking
####################################################################
echo "####################################################################"
echo "### FILE TWEAKING"
echo "####################################################################"
#2d_eig test script tweak
sed -e "s:makenek :makenek.bb :g" \
    -e "s:^doit:\.\/doit_test:" ./examples/2d_eigtest/doall > ./examples/2d_eigtest/doall_test
sed -e "s:makenek :\.\/makenek.bb :g" \
    -e "s:clean:clean .\/nek:" \
    -e "s:^nekl:\.\/nekl:" ./examples/2d_eigtest/doit > ./examples/2d_eigtest/doit_test
chmod +x ./examples/2d_eigtest/doall_test
chmod +x ./examples/2d_eigtest/doit_test

#Tweak SIZE files 
sed -i "s:lx2=.*:lx2=lx1):"  examples/*/SIZE
sed -i "s:lx2=.*:lx2=lx1):"  examples/cone/*/SIZE
sed -i "s:ly2=.*:ly2=ly1):"  examples/*/SIZE
sed -i "s:ly2=.*:ly2=ly1):"  examples/cone/*/SIZE
sed -i "s:lz2=.*:lz2=lz1):"  examples/*/SIZE
sed -i "s:lz2=.*:lz2=lz1):"  examples/cone/*/SIZE

# MOAB
if [ "${IF_MOAB}" == "on" ]
then
    sed -i "s:(lx1=4,ly1=lx1,lz1=lx1,lelt=1500,lelv=lelt):(lx1=4,ly1=lx1,lz1=lx1,lelt=6000,lelv=lelt):" examples/moab/SIZE
fi

sed -i "s:(lx1=10,ly1=lx1,lz1=1,lelt=80,lelv=lelt):(lx1=8,ly1=lx1,lz1=1,lelt=80,lelv=lelt):" examples/vortex2/SIZE
sed -i "s:(lxd=15,lyd=lxd,lzd=1):(lxd=12,lyd=lxd,lzd=1):" examples/vortex2/SIZE

#Tweak .rea files 
cd ./examples/eddy/
sed "s/^.*DIVERGENCE$/  0.10000E-08/" eddy_uv.rea > n.rea
mv n.rea eddy_uv.rea
cd ../lowMach_test
sed "s/^.*IFNAV.*$/  T T IFNAV & IFADVC/" lowMach_test.rea > n.rea
mv n.rea lowMach_test.rea

# MOAB
if [ "${IF_MOAB}" == "on" ]
then
    cd ../moab
    sed -i "s/^.*p15.*$/ 100&/" pipe.rea
fi

cd ../vortex2
sed -i "s/^.*p11.*$/ 8000&/" v2d.rea

cd ../../
##############################################################
### Builds tools with serial compilers
##############################################################
echo "####################################################################"
echo "### BUILD TOOLS"
echo "####################################################################"

cd ./trunk/tools/
build_tools ${F77_SRL} ${CC_SRL} ${HERE}/tools.out

# we run tests from trunk/nek
cd ../nek/

##############################################################
##############################################################
### Test Pn-Pn Case
##############################################################
##############################################################
PERFORMED_TESTS_L=""
echo "####################################################################"
echo "### START TESTS PN-PN CASE"
echo "####################################################################"

####### Parallel ########
if [ "${IF_MPI}" == "on" ]
then
    echo "####################################################################"
    echo "### PARALLEL"
    echo "####################################################################"
    PERFORMED_TESTS=''
# set compiler and create makenek.bb
    sed -e "s:^F77*=\"mpif77\":F77=\"${F77_MPI}\":"  \
	-e "s:^CC*=\"mpicc\":CC=\"${CC_MPI}\":"  makenek > makenek.bb
    chmod +x makenek.bb

    if [ "${IF_MOAB}" == "on" ]
    then
#Tweak MOAB makenek
	cd ../../examples/moab
	cp ../../trunk/nek/makenek.bb .
	sed -e "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"${MOAB_LIB_S}\"/" \
	    -e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
	    -e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"${MOAB_DIR_PAR_S}\":" makenek.bb>t.t
	mv t.t makenek.bb
	chmod +x makenek.bb
	cd ../moab_conjht
	cp ../../trunk/nek/makenek.bb .
	sed -e "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"${MOAB_LIB_S}\"/" \
	    -e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
	    -e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"${MOAB_DIR_PAR_S}\":" makenek.bb>t.t
	mv t.t makenek.bb
	chmod +x makenek.bb
	cd ../../trunk/nek
    fi

#Remove old map files and Start Parallel Tests!
    rm -rf ../../examples/*/*.map
    source ../../tests/ExTestmpi

    moveLog ../../tests/mpiLog

# test list
    for i in $PERFORMED_TESTS
    do
	PERFORMED_TESTS_L=${PERFORMED_TESTS_L}' mpi'$i
    done
fi

####### Serial ########
echo "####################################################################"
echo "### SERIAL"
echo "####################################################################"
PERFORMED_TESTS=''
# set compiler and create makenek.bb
submake ${F77_SRL} ${CC_SRL}

if [ "${IF_MOAB}" == "on" ]
then
#Tweak MOAB makenek
    cd ../../examples/moab
    cp ../../trunk/nek/makenek.bb .
    sed -e "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"${MOAB_LIB_S}\"/" \
	-e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
	-e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"${MOAB_DIR_SRL_S}\":" makenek.bb>t.t
    mv t.t makenek.bb
    chmod +x makenek.bb
    cd ../moab_conjht
    cp ../../trunk/nek/makenek.bb .
    sed -e "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"${MOAB_LIB_S}\"/" \
	-e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
	-e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"${MOAB_DIR_SRL_S}\":" makenek.bb>t.t
    mv t.t makenek.bb
    chmod +x makenek.bb
    cd ../../trunk/nek
fi

#Start Tests
source ../../tests/ExTest
moveLog ../../tests/srlLog

# test list
for i in $PERFORMED_TESTS
do
    PERFORMED_TESTS_L=${PERFORMED_TESTS_L}' srl'$i
done

##############################################################
##############################################################
### Test Pn-Pn-2 Case
##############################################################
echo "####################################################################"
echo "### START TESTS; PN-PN-2 CASE"
echo "####################################################################"
##############################################################
### File tweaking
##############################################################
# Tweak SIZE files 
cd ../../
sed -i "s:lx2=.*:lx2=lx1-2):"  examples/*/SIZE
sed -i "s:lx2=.*:lx2=lx1-2):"  examples/cone/*/SIZE
sed -i "s:ly2=.*:ly2=ly1-2):"  examples/*/SIZE
sed -i "s:ly2=.*:ly2=ly1-2):"  examples/cone/*/SIZE

sed -i "s:lz2=.*:lz2=lz1-2):"  examples/vortex/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/3dbox/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/expansion/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/hemi/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/mhd/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/peris/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/pipe/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/solid/SIZE
sed -i "s:lz2=.*:lz2=lz1-2):"  examples/turbChannel/SIZE
#MOAB
if [ "${IF_MOAB}" == "on" ]
then
    sed -i "s:lz2=.*:lz2=lz1-2):"  examples/moab/SIZE
    sed -i "s:lz2=.*:lz2=lz1-2):"  examples/moab_conjht/SIZE
fi


# we run tests from trunk/nek
cd ./trunk/nek

####### Parallel ########
if [ "${IF_MPI}" == "on" ]
then
    echo "####################################################################"
    echo "### PARALLEL"
    echo "####################################################################"
    PERFORMED_TESTS=''
# New makenek
    sed -e "s:^F77*=\"mpif77\":F77=\"${F77_MPI}\":"  \
	-e "s:^CC*=\"mpicc\":CC=\"${CC_MPI}\":"  makenek > makenek.bb
    chmod +x makenek.bb

    if [ "${IF_MOAB}" == "on" ]
    then
#Tweak MOAB makenek
	cd ../../examples/moab
	cp ../../trunk/nek/makenek.bb .
	sed -e "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"${MOAB_LIB_S}\"/" \
	    -e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
	    -e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"${MOAB_DIR_PAR_S}\":" makenek.bb>t.t
	mv t.t makenek.bb
	chmod +x makenek.bb
	cd ../moab_conjht
	cp ../../trunk/nek/makenek.bb .
	sed -e "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"${MOAB_LIB_S}\"/" \
	    -e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
	    -e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"${MOAB_DIR_PAR_S}\":" makenek.bb>t.t
	mv t.t makenek.bb
	chmod +x makenek.bb
	cd ../../trunk/nek
    fi

#Remove old map files and start testing
    rm -rf ../../examples/*/*.map
    source ../../tests/ExTestmpi

    moveLog ../../tests/mpi2Log

# test list
    for i in $PERFORMED_TESTS
    do
	PERFORMED_TESTS_L=${PERFORMED_TESTS_L}' mpi2'$i
    done
fi

####### Serial ########
echo "####################################################################"
echo "### SERIAL"
echo "####################################################################"
PERFORMED_TESTS=''
# set compiler and create makenek.bb
submake ${F77_SRL} ${CC_SRL}

if [ "${IF_MOAB}" == "on" ]
then
#Tweak MOAB makenek
    cd ../../examples/moab
    cp ../../trunk/nek/makenek.bb .
    sed -e "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"${MOAB_LIB_S}\"/" \
	-e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
	-e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"${MOAB_DIR_SRL_S}\":" makenek.bb>t.t
    mv t.t makenek.bb
    chmod +x makenek.bb
    cd ../moab_conjht
    cp ../../trunk/nek/makenek.bb .
    sed -e "0,/^#USR_LFLAGS.*/s//USR_LFLAGS=\"${MOAB_LIB_S}\"/" \
	-e "s:^#PPLIST=\"?\":PPLIST=\"MOAB\":" \
	-e "s:^#MOAB_DIR=\"\$HOME\/moab\":MOAB_DIR=\"${MOAB_DIR_SRL_S}\":" makenek.bb>t.t
    mv t.t makenek.bb
    chmod +x makenek.bb
    cd ../../trunk/nek
fi

#Start testing
source ../../tests/ExTest
moveLog ../../tests/srl2Log

# test list
for i in $PERFORMED_TESTS
do
    PERFORMED_TESTS_L=${PERFORMED_TESTS_L}' srl2'$i
done

PERFORMED_TESTS=$PERFORMED_TESTS_L

####Return to test directory#######
cd $HERE
